name: dictionary
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  elementary: ^1.3.1
  shared_preferences: ^2.0.15
  get_it: ^7.2.0
  flutter_displaymode: ^0.4.0
  file_picker: ^4.6.1
  flutter_tts: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.8.2
  import_sorter: ^4.6.0

flutter:
  uses-material-design: true


